title:
description: Systematic futures spread betting with IG
theme: just-the-docs

url: https://bug-or-feature.github.io/pst-fsb-site/

aux_links:
  Project repo: https://github.com/bug-or-feature/pysystemtrade-fsb
